{% set version = "12.6.6" %}

package:
  name: armadillo
  version: {{ version }}

source:
  fn: armadillo-{{ version }}.tar.xz
  url: https://sourceforge.net/projects/arma/files/armadillo-{{ version }}.tar.xz
  sha256: 3858b0fd431772af032ad3f35c2aeb54e8dabea59169e7d1e9fccd78bc82ad35

build:
  number: 0
  skip: true  # [win and vc<14]
  # Armadillo doesn't support MKL on macOS
  skip: true  # [osx and (blas_impl != 'openblas')]
  run_exports:
    - {{ pin_subpackage('armadillo', min_pin='x.x', max_pin='x') }}
  missing_dso_whitelist:
    - '$RPATH/ld64.so.1'  # [s390x]

requirements:
  build:
    - cmake >=3.1
    - make  # [unix]
    - {{ compiler('cxx') }}
    - pkg-config  # [unix]
    - ninja  # [win]
  host:
    # Our openblas package provides liblapack. ALso, libpapack is a symlink to openblas.
    - openblas-devel {{ openblas }}  # [blas_impl == 'openblas']
    - mkl-devel {{ mkl }}  # [blas_impl == 'mkl']
    - arpack  # [unix]
    - superlu >=5.2.0,<6  # [unix]
  run:
    - arpack  # [unix]
    - superlu >=5.2.0,<6  # [unix]
    # OpenBLAS or MKL
    - mkl {{ mkl }}.*                 # [blas_impl == "mkl"]
    - libopenblas                     # [blas_impl == "openblas"]

test:
  commands:
    - test -f "${PREFIX}/include/armadillo"  # [unix]
    - test -d "${PREFIX}/include/armadillo_bits"  # [unix]
    - test -f "${PREFIX}/lib/libarmadillo${SHLIB_EXT}"  # [unix]
    - if not exist %LIBRARY_INC%\armadillo_bits exit 1  # [win]
    - if not exist %LIBRARY_INC%\armadillo exit 1  # [win]
    - if not exist %LIBRARY_LIB%\armadillo.lib exit 1  # [win]

about:
  home: https://arma.sourceforge.net/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Armadillo C++ linear algebra library
  description: |
    Armadillo is a high quality C++ library for linear algebra and scientific computing,
    aiming towards a good balance between speed and ease of use.
  dev_url: https://gitlab.com/conradsnicta/armadillo-code
  doc_url: https://arma.sourceforge.net/docs.html

extra:
  recipe-maintainers:
    - grlee77
    - dirmeier
    - marcelotrevisani
    - henryiii
