{% set version = "8.500.0" %}
{% set variant = "openblas" %}

package:
    name: armadillo
    version: {{ version }}

source:
    fn: armadillo-{{ version }}.tar.xz
    url: http://sourceforge.net/projects/arma/files/armadillo-{{ version }}.tar.xz
    sha256: f51c69f45cfbd4773c77ded333c8ff9cdd9a8e0d5a1c011b6a0333ab4b8cbbf1
    patches:
        # have to add additional ${PREFIX}/lib etc... to tests/Makefile
        - make_tests.patch  # [linux]
        - make_tests_osx.patch  # [osx]
        # modify CMakeLists to use OpenBLAS rather than Accelrate on OS X
        # and to use OpenBLAS as the LAPACK library on linux
        - CMakeLists.patch

build:
  number: 202
  skip: true  # [win32]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - cmake
    - m2w64-toolchain  # [win]
    # optional items below here
    - pkg-config  # [not win]
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
    - arpack  # [not win]
    - superlu 5.2  # [not win]
  run:
    - m2w64-toolchain  # [win]
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
    - arpack  # [not win]
    - superlu 5.2  # [not win]

test:
  commands:
    - test -f "${PREFIX}/include/armadillo"  # [not win]
    - test -d "${PREFIX}/include/armadillo_bits"  # [not win]
    - test -f "${PREFIX}/lib/libarmadillo${SHLIB_EXT}"  # [not win]
    - dir %LIBRARY_INC%  # [win]
    - dir %LIBRARY_LIB%  # [win]
    - dir %LIBRARY_INC%\armadillo  # [win]
    - if not exist %LIBRARY_INC%\armadillo_bits exit 1  # [win]
    - if not exist %LIBRARY_INC%\armadillo exit 1  # [win]
    - if not exist %LIBRARY_LIB%\armadillo\libarmadillo.dll exit 1  # [win]

about:
    home: http://arma.sourceforge.net
    license: Apache 2.0
    license_file: LICENSE.txt
    summary: Armadillo C++ linear algebra library

extra:
    recipe-maintainers:
      - grlee77
      - dirmeier
      - marcelotrevisani
