{% set version = "8.300.4" %}
{% set variant = "openblas" %}

package:
    name: armadillo
    version: {{ version }}

source:
    fn: armadillo-{{ version }}.tar.xz
    url: http://sourceforge.net/projects/arma/files/armadillo-{{ version }}.tar.xz
    sha256: 97af66cba7afa21d742d234ecdf06957c9a2e9ac6b55dd4cfd362ebcb48f5bba
    patches:
        # have to add additional ${PREFIX}/lib etc... to tests/Makefile
        - make_tests.patch  # [linux]
        - make_tests_osx.patch  # [osx]
        # modify CMakeLists to use OpenBLAS rather than Accelrate on OS X
        # and to use OpenBLAS as the LAPACK library on linux
        - CMakeLists.patch

build:
  number: 201
  skip: true  # [win]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - cmake
    # optional items below here
    - pkg-config
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
    - arpack
    - superlu 5*
    # - hdf5 1.8.17|1.8.17.*
  run:
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
    - arpack
    - superlu 5*
    # - hdf5 1.8.17|1.8.17.*

test:
  commands:
    - test -f "${PREFIX}/include/armadillo"
    - test -d "${PREFIX}/include/armadillo_bits"
    - test -f "${PREFIX}/lib/libarmadillo.so"  # [linux]
    - test -f "${PREFIX}/lib/libarmadillo.dylib"  # [osx]

about:
    home: http://arma.sourceforge.net
    license: Apache 2.0
    license_file: LICENSE.txt
    summary: Armadillo C++ linear algebra library

extra:
    recipe-maintainers:
      - grlee77
      - dirmeier
