# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "S/AIRcz1XaMlc04ybW+2odBq8sYcVTuB9fjl//tgu1qLMc7j2nINFRvIF1b6yY3xMey8KeY9h9sBZ+uSsc4CYE2NQvaB2oTromXCcCrH7/jzsgRDntzaT36Ttk0tZLPEVTG0RG5i8U0MikJd8/YbOLirpGGpwXoavUX4DSwhKq1A5SqiuqByKwdHRowgOQFfyn5cwzuC46LQ0+949Bxrjj9rZbEVKjLfL1V2gQpbXbXTn4aiScJLnJgR/qt1ypSdvTfZfQ0p9+GiIkiF9dGcS+g2z5a6Ca21VBSf7ePwWOqBjk9Or8H6dj6devw56qQ/cg7akxy90Pv7OmR+g+HGx/6HDfNIgDsPG2MCccMIUCSZ0zResMz/v2s0zMsiMYVsKyBLGkz94FrZJN+i86oqO8SjUFiC5HWQMtuHx3HuwurVfEvrCaYNizhHQ51ps6AWr2IQ/DRnV6ZaQe7rss/GEaFzDk1un7PMyq8EvKHLbf3db8i3XTmnYYH4rxMNC5xCEMkLoGfa1vVcUpRetikGtnTdeSoOModzsxMuaPa5srs7e+GTJzgOoRFtvYuPCxPD1EfAtSg7NwwQgoP/PLcGxa30EGG31jqul6ZnK2BqfDlcNGsN+YjQCDAUpSjj2yScaHDnMAnddjrMsJ1KtUVULVzy4XQudQG5myYX8u56Kgk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
