# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "DP+XTYnOH2f51qS/pwpSg7azudG2zfbT3bRj/U0yRfQYkfhUH/HXAaE0RkjVf9ti4HKV2meYXnCzTLiuVmjAG4If10b5aRSefQhkZv2kAyZfNkCjOd9p1GfpaC8l9k+2awBRTT3jl1vlj5updPG5xEgbDJBwy7E4BtbvYzqu1BzTfn3VQ3bc944pLhkVojOHqdmq7olK4xVGYb0/30FON+Am1rd9iqoA6moFN2YnAvflgxT53065wa0tUM+tuu/tHN//yqH7TCfvffpMRigCxPYNLdZ7+0gsl2AoGcyw1e7M5UY/1nmK2flsWTpQbvV5GWZ/rFtHLz7ub3TB34mDqT98e2bvVfyIy2FvSDYFDkgNOj5VOXLgJyWi10uvBvMDQja4AGEzr+FDWOaLf6iQ1BV06CJzaHtJnviA7jg/GrKyk5wyk8j/xGKc4UIDzVKbeYO0/e6x/5BnFar8H0CR/F1qzPgt4qZnBKGyMjg5hbXcEgsN0poRazAMm7/HwmdhXhZ+eRE9oiyy1e7TqwQ7xqGQ2Kg0oJK1o2TIkE/6+PMtP66fZrYKq1Qfoz+Avq6b1pgBjud9XXFSOPzqUJnKPRL9K72IX7nsTcTqipPSs/5Noin729Yc8BfT3pJpcBoYQA3YaFP+ug1w0yiIpGF3vqSUaj6zlKIpND6O1w0EFDs="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
