travis:
  secure:
    BINSTAR_TOKEN: S/AIRcz1XaMlc04ybW+2odBq8sYcVTuB9fjl//tgu1qLMc7j2nINFRvIF1b6yY3xMey8KeY9h9sBZ+uSsc4CYE2NQvaB2oTromXCcCrH7/jzsgRDntzaT36Ttk0tZLPEVTG0RG5i8U0MikJd8/YbOLirpGGpwXoavUX4DSwhKq1A5SqiuqByKwdHRowgOQFfyn5cwzuC46LQ0+949Bxrjj9rZbEVKjLfL1V2gQpbXbXTn4aiScJLnJgR/qt1ypSdvTfZfQ0p9+GiIkiF9dGcS+g2z5a6Ca21VBSf7ePwWOqBjk9Or8H6dj6devw56qQ/cg7akxy90Pv7OmR+g+HGx/6HDfNIgDsPG2MCccMIUCSZ0zResMz/v2s0zMsiMYVsKyBLGkz94FrZJN+i86oqO8SjUFiC5HWQMtuHx3HuwurVfEvrCaYNizhHQ51ps6AWr2IQ/DRnV6ZaQe7rss/GEaFzDk1un7PMyq8EvKHLbf3db8i3XTmnYYH4rxMNC5xCEMkLoGfa1vVcUpRetikGtnTdeSoOModzsxMuaPa5srs7e+GTJzgOoRFtvYuPCxPD1EfAtSg7NwwQgoP/PLcGxa30EGG31jqul6ZnK2BqfDlcNGsN+YjQCDAUpSjj2yScaHDnMAnddjrMsJ1KtUVULVzy4XQudQG5myYX8u56Kgk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
