travis:
  secure:
    BINSTAR_TOKEN: b7YpQcP3rM7M1aMhtHjcHY2CsUG/4ZP1zOemoWFan9tn3Ip4XY8HItnWac/ABIb/JhK4Q+iPYxd5u8+owZH35i1VpnN1yc722SMvyR587l/fhhvOYJGZYntPCzhlOozraM/QeEAPCag3u9F33hh1C2XhsG51rdd6M328ydjXf+AzU1zRbV+mpxPJWPPSuPGZEpEjZXCzS3IRYWGwwYqu1tAJIzcH2sbvLlG5CL0ra4dmeydgFR98Xl0sj4sWfyzkXb4rNrptR+hh6ihsXQto+YMHSFV+IlAdVU5v526quJtKZmpJcMVPsMIlTgGNPnXco6ZNAhe+NzL/OafTrzBddvnl/bbSN2QUV33l9ze1A07UbozcxZCRSHx4Kmh9lic10Q71PFk9n1QZWIccsbDpYjrvs7zRay8RrbvJSjR5S4n+5KyiAP6/6L6hyNRi/Ndk1i9IXWOfDRyXStV7hv/wpHFINYqJ2pi8B0fCvdrWhzr33XirEH6vI4YFbEdRSohiFeGh8SXjPeotjtErfSRt469NMpkFGtxkJ1ifIsZHjWtqk9evJKcFjzqjUP2iT55Y/GHU5FWALIEsKdS/0r5gXfk2nZlQp9FkxJ3Z8zCN4YNPvTeqnh34eaLOiMLWpDjDlm75VKnPHAkLBY+0MM3yaqMeEdmI0aDGTH+aZtVuV5w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
