travis:
  secure:
    BINSTAR_TOKEN: tCw5f2fB59owydixJWmIxmuBKYusmBJi8H0IVEV43dpWF/REsROFq1a56TePhifXQMEhtnW5NO6HDqPIR3b5kZ+tEpd12+V22HYmgXZ3QNaZ4lcQN9JSBXpp1/H/HQtLKBzgXZdwbiqFKd8VP9O+cmjP2HUbDw+2VyMwWJvnOa/JEztJrPxxfnxd7fSzqHCGWQGAi4BaMKFc7xxyaW99jOIboCcWKiLc4H4sYbWjNx+bZknOZBKMxFAk2Pj7EobBLzcSqamLm+yIiaLEzZsvD3CLc5G92o8uzHXXnxDaBVRJtdJE5cmMY/HI/xupTFe+47IvBdoIeiPEL7V2u6yukoh9WnBDwaMl7ByO718z5RB+KUrJgwv8o/R6mm/h0N5DfbBSDGfhhwUDiLBLYdix3XB/jxwmp4F8UB7Z4uaGwuVMFGvyoL/Caq4i6gxSXq0m3fzzUx3/zCGEwe0Frw4zecJR1MnsPLNDVmUAkv6FSl3gNmdz74K7mSSwkSDlrprLsn/dsy5IWZR7G3FrzuPUJrviu0WVMoqlOtRfNsq9KdbwHu8d/rRfB3IfA55JNohZWx3i7qCLdHwJMH/JBKoTiI470sVOU44t5xh+Bui90uW73Ncx+Ni4102ZL3UX7mIfUGEHaotdyE+qUoZei8IUPRk0B8YuAink5A/rmdbsgwY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
