travis:
  secure:
    BINSTAR_TOKEN: K52nJijEVuYz9TdUkG60MPEjj/1JHakwB7XeDzgRKR0mMeACcv5MIle/JqQ/3sQW5Ul+xaSopjfOd/wEhPuTASOd6AVQisfPdrwRKRM5bIDH/CjTeL9SB1VADOl49cZT9n57E13v4QqglHFTdDN57S9/CkNPpAwlzVaBOtT/kmIgBx7MffleRobzklHZyZZnB4V5lMtA0S6zBLb3o/IFBJYgbNxOvd0/PoFOplqXpcpsOulGv1lYQsYithpBFUd8szMkFMlt7ygtCIHRpc/phHnMIoxdpPsP77LGa33rLqKX6a7iL/GGIlB5a6F1dtQJSbBidpc2+4aaP2FcpJYjBT47E8Ngu1d3zN0iYDUTa59InwTmjdZeSBQH4z6P13xaaqoaJTWYkrEUl7J04x2UIjT0CUtL6xyEZgem0y8c5xxWhzr5Ttc273Aci2i3/T6RSWfg8Te16qjzyh5iy5f1q+LmohpfS03zSHSQtxfLlr4aglOhnBEcI7rUtSukU67WHKRlm3+vhIxDwfmMlozla7292qzM8omyL2Y9M95KwAqD8efNgNEYsbiwQMDHfa6siBQgaxoaGdLoEA6fbCgW1Da5rR/Naft04fCLv5lWGPBdoRbajz1LPLEi4W/VDZo1vfutF9QnUam71IRrzmLq7Z5bPv4GBUnL5o6u+PM7x5c=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
